# -*- coding: utf-8 -*-
"""VISUALISASI DATA DAN STATISTIKA DESKRIPTIF DENGAN PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wy2dTo3xtOzHI0_soOtwc70vz62mGExT
"""

import matplotlib.pyplot as plt
import pandas as pd

path = "reginald.xlsx"
dataraw = pd.read_excel(path)

dataraw = pd.read_excel(path, skiprows=7)
print(dataraw.columns)

print(dataraw.head())

datafrq = pd.crosstab(index=dataraw["Grade"], columns="Frekuensi")
print(datafrq)

plt.figure(figsize=(8, 4))
datafrq.plot(kind="line", marker="o", color="#1f77b4", legend=True)
plt.title("Grafik Garis Frekuensi Grade")
plt.xlabel("Grade")
plt.ylabel("Frekuensi")
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
datafrq.plot(kind="bar", color="#4c72b0", edgecolor="black")
plt.title("Grafik Batang Frekuensi Grade")
plt.xlabel("Grade")
plt.ylabel("Frekuensi")
plt.xticks(rotation=0)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 6))
datafrq.plot(
    kind="pie",
    y="Frekuensi",
    autopct="%1.0f%%",
    legend=False,
    colors=["#5b9bd5", "#ed7d31", "#a5a5a5", "#ffc000", "#70ad47", "#9e480e"],
)
plt.title("Distribusi Persentase Grade Mahasiswa")
plt.ylabel("")
plt.tight_layout()
plt.show()

dataraw["Final Score"] = pd.to_numeric(
    dataraw["Final Score"], errors="coerce"
)
dataraw["Final Score"] = pd.to_numeric(
    dataraw["Final Score"], errors="coerce"
)
dt = dataraw["Final Score"]

stats = dt.describe()
stats["Standard Error"] = dt.sem()
stats["Median"] = dt.median()
stats["Mode"] = dt.mode().iloc[0]
stats["variance"] = dt.var()
stats["range"] = dt.max() - dt.min()
stats["skewness"] = dt.skew()
stats["kurtosis"] = dt.kurtosis()

print("\n--- Hasil Statistika Deskriptif ---")
print(stats)